<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-DE53235" failures="1" tests="5" name="org18.validationInTestNG.Example1" time="89.800" errors="0" timestamp="2024-12-23T10:02:31 IST" skipped="0">
  <testcase classname="org18.validationInTestNG.Example1" name="testActiTimeCheckbox" time="18.392"/>
  <system-out/>
  <testcase classname="org18.validationInTestNG.Example1" name="testActiTimeUsernameField" time="16.841"/>
  <system-out/>
  <testcase classname="org18.validationInTestNG.Example1" name="testActiTimeLoginWithEquals" time="14.979"/>
  <system-out/>
  <testcase classname="org18.validationInTestNG.Example1" name="testActiTimeLoginWithAssert1" time="16.521">
    <failure message="Login failed, either title changes or invalid password entered expected [actiTIME - Login] but found [actiTIME - Enter Time-Track]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Login failed, either title changes or invalid password entered expected [actiTIME - Login] but found [actiTIME - Enter Time-Track]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org18.validationInTestNG.Example1.testActiTimeLoginWithAssert1(Example1.java:31)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testActiTimeLoginWithAssert1 -->
  <system-out/>
  <testcase classname="org18.validationInTestNG.Example1" name="testActiTImeLoginWithAssert2" time="23.067"/>
  <system-out/>
</testsuite> <!-- org18.validationInTestNG.Example1 -->
